### ISSUE TITLE
New release for Drupal 8.8

### ISSUE THREAD

**Issue by pfrenssen** [Gizra/og#576]
We should make a new release as soon as possible that is compatible with Drupal 8.8.0 which was released yesterday. The current release breaks badly on it due to #572 (which is already fixed in dev).

I think once we get a green build on 8.8.0 we should be good to go. Here is a list of issues to focus on:

- [x] #519 Providing settings under 'handler_settings' is deprecated
- [x] #552 Drupal\system\Plugin\views\field\BulkForm is deprecated
- [x] #553 Calling BulkForm::__construct() with the $entity_repository argument is required
- [x] #579 Any entity_reference_autocomplete component of an entity_form_display must have a match_limit setting
- [x] #582 Drupal\Tests\BrowserTestBase::$defaultTheme is required
- [x] #585 Require tests on Drupal 8.8.x to pass in the test matrix
- [x] #586 EntityType::getLowercaseLabel() is deprecated in 8.8.0
- [x] #588 Using assertTrue() in a nonstrict way is deprecated
- [x] #591 Fix DrupalConsoleAddFieldTest::testNewGroup() failure with 8.8.0

**Comment by claudiu-cristea** [comment]
Add also #579 to the list.

**Comment by claudiu-cristea** [comment]
#582 should be added

**Comment by claudiu-cristea** [comment]
#586 should be added

**Comment by claudiu-cristea** [comment]
#588 should be added

**Comment by claudiu-cristea** [comment]
#591 should be added

**Comment by pfrenssen** [comment]
All is done thanks to the awesome work by @claudiu-cristea who single handedly implemented 9 PRs in 4 days to get this release out the door!! Thanks a lot!!!

https://github.com/Gizra/og/releases/tag/8.x-1.0-alpha4

**Comment by amitaibu** [comment]
Thank you @claudiu-cristea and @pfrenssen !

**Comment by MPParsley** [comment]
Awesome work!

We still may have to check some of the outstanding beta feature branches for conflicts or 8.8 issues.
